name: Build Latest

concurrency:
    group: "build"
    cancel-in-progress: true

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: "21"
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              run: ./gradlew build
            - name: Remove *-dev.jar
              run: rm ./build/libs/*-dev.jar || true
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "build-tag"
                  prerelease: false
                  title: "Build"
                  files: |
                      ./build/libs/*.jar
